services:
  db:
    restart: always

  redis:
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always

  celery_worker:
    restart: always

  celery_beat:
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always

  nginx:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media_files:/media:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
